"""Static readings of an authored page.

This facade keeps the pre-split import surface intact while the structural,
passage, and style readers move to their owning modules.
"""

from .passages import (  # noqa: F401
    COLLAPSE,
    COLLAPSE_CHARS,
    CONTEXT,
    EMPTY,
    TEXT_BLOCK_TAGS,
    UNQUOTABLE_TAGS,
    Passages,
    Spoken,
    _PassageParser,
    _removed_by,
    capture_anchor,
    collapse,
    enclosing_section,
    occurrences,
    page_passages,
    section_span,
    spoken,
)
from .structure import (  # noqa: F401
    COLUMN_FALLBACK,
    COLUMN_SELECTORS,
    DOCUMENT_WRAPPERS,
    HEAD_METADATA_TAGS,
    LANGUAGE_CLASS,
    LF_META,
    OPTIONAL_END,
    OVERFLOW_PROPS,
    P_CLOSERS,
    PAGE_CSP,
    PIXEL_WIDTH_TAGS,
    POINTABLE_TAGS,
    SECTIONING_TAGS,
    SIBLING_CLOSERS,
    VOID_TAGS,
    _names_column,
    _StructParser,
    _versions,
    implicit_closes,
    parse_structure,
    parse_version,
    version_review_mode,
)
from .styles import (  # noqa: F401
    PRESENTATION_PROPERTIES,
    _column_width,
    _css_unclosed_blocks,
    _lone_px,
    _number,
    _overwide_elements,
    _px,
    _px_widths,
    _rules,
    css_block,
    css_rules,
    css_syntax_errors,
    inline_presentation_override_errors,
    root_tokens,
)
