// Bundle the selected controls and only the upstream theme, scoped to their owner.
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

const [out, version] = process.argv.slice(2);
const css = await build({
  entryPoints: ["node_modules/@awesome.me/webawesome/dist/styles/themes/default.css"],
  bundle: true,
  minify: true,
  write: false,
});
// Each component host owns its theme defaults. Authored content never inherits
// upstream typography; the same selectors work inside declared shadow roots.
const hosts =
  "wa-color-picker, wa-copy-button, wa-comparison, wa-switch, wa-radio-group, wa-radio, wa-slider, wa-select, wa-option, wa-input, wa-textarea, wa-number-input";
const leafTheme = await readFile("leaf-theme.css", "utf8");
const theme = `/* Generated by scripts/vendor.py webawesome. Web Awesome ${version} — MIT; see vendor/webawesome.LICENSES.txt */\n@layer lf-vendor{@scope (:is(${hosts})){${css.outputFiles[0].text.replaceAll(":root", ":scope")}}\n${leafTheme}}`;

await writeFile(
  "theme.mjs",
  `import { registerWidgetStyles } from "/runtime/shadow-stage.js";
registerWidgetStyles("Web Awesome", ${JSON.stringify(theme)});`,
);
// Lit is the page's one copy in /vendor/lit.js, which scripts/browser/build.mjs
// builds in the shape of Lit's `lit-all` bundle: every public module's exports in
// one namespace, with static-html's tags renamed so they keep their own names here.
const lit = {
  name: "leaf-lit",
  setup(build) {
    build.onResolve({ filter: /^lit\/static-html\.js$/ }, () => ({
      path: "static-html",
      namespace: "leaf-lit",
    }));
    build.onLoad({ filter: /.*/, namespace: "leaf-lit" }, () => ({
      contents:
        'export { staticHtml as html, staticSvg as svg, staticMathml as mathml, literal, unsafeStatic, withStatic } from "/vendor/lit.js";',
    }));
    build.onResolve({ filter: /^lit(\/|$)/ }, () => ({
      path: "/vendor/lit.js",
      external: true,
    }));
  },
};
const result = await build({
  entryPoints: { "webawesome.esm": "entry.mjs", "webawesome-chrome": "chrome.mjs" },
  splitting: true,
  chunkNames: "webawesome/[name]-[hash]",
  external: ["/runtime/shadow-stage.js", "/vendor/lit.js"],
  plugins: [lit],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "chrome105",
  minify: true,
  legalComments: "inline",
  metafile: true,
  outdir: out,
  banner: {
    js: `/*! Web Awesome ${version} — MIT — licenses: webawesome.LICENSES.txt */`,
  },
});
// Record exactly the packages esbuild consumed, including transitive runtime code.
const packages = new Set(
  Object.keys(result.metafile.inputs)
    .map((path) => {
      const tail = path.split("node_modules/").at(-1);
      const parts = tail.split("/");
      return path.includes("node_modules/")
        ? parts.slice(0, parts[0].startsWith("@") ? 2 : 1).join("/")
        : null;
    })
    .filter(Boolean),
);
await writeFile("packages.json", JSON.stringify([...packages].sort()));
