"""Generate examples/corpus.html: the composable authored fixtures on one page.

The corpus is derived test content — edit a listed example, regression page, or
developer gallery and rerun `leaf-dev corpus` (tests fail on a stale corpus). Each page's
<main> body keeps its ids but not its document-level contents sidebar. Every source
must therefore keep its ids disjoint, which this command enforces.
An example that owns an element (a page/registry.json declaration with its module under
page/widgets/) brings that element into the corpus through examples/corpus.page/, the
corpus's own page directory, so its markup still names a declared element there.

    uv run leaf-dev corpus
"""

import html
import json
import re
import shutil
import sys

import click
from leaf.structure import SourceDocument
from leaf.thread_context import sample_events, thread_ids

from leaf_dev import ROOT
from leaf_dev.example_data import regression_sources

EXAMPLES_DIR = ROOT / "examples"
CORPUS = EXAMPLES_DIR / "corpus.html"
CORPUS_DATA = EXAMPLES_DIR / "corpus.data.json"
CORPUS_EVENTS = EXAMPLES_DIR / "corpus.jsonl"
CORPUS_PAGE = EXAMPLES_DIR / "corpus.page"
# Keep the short core pages first; specialist and regression surfaces follow.
PUBLIC_TABS = [
    ("review-a-plan", "Plan review"),
    ("triage-board", "Triage"),
    ("ideas-to-implement", "Ideas"),
    ("release-notes", "Notes"),
    ("log-retention", "Retention"),
    ("ship-review", "Ship review"),
    ("heat-loss", "Heat"),
    ("notification-playground", "Notification"),
    ("data-explorer", "Data explorer"),
    ("code-comparison", "Code comparison"),
    ("live-progress", "Live"),
    ("alert-review", "Alerts"),
    ("pr-walkthrough", "PR"),
    ("wt-merge", "Merge film"),
    ("rust-sort", "Sort film"),
    ("security-boundary", "Security"),
    ("command-hub", "Command"),
    ("annotation-workspace", "Annotation workspace"),
]
# Focused chrome galleries with several live child pages stay separate; their
# underlying widget and thread states already stand in the feature gallery.
DEVELOPER_TABS = [
    (EXAMPLES_DIR / "developer" / "feature-gallery.html", "Core features"),
    (EXAMPLES_DIR / "developer" / "swipe-gallery.html", "Swipe package"),
    (EXAMPLES_DIR / "developer" / "targeting-gallery.html", "Targeting package"),
    (
        EXAMPLES_DIR / "developer" / "visual-review-gallery.html",
        "Visual review package",
    ),
]
CONTENTS_MAP = re.compile(
    r"\s*<(aside|section)\b[^>]*>\s*<lf-toc\b[^>]*></lf-toc>\s*</\1>"
)
TABS = [
    *((EXAMPLES_DIR / f"{stem}.html", label) for stem, label in PUBLIC_TABS),
    *(
        (source, source.stem.replace("-", " ").title())
        for source in regression_sources()
    ),
    *DEVELOPER_TABS,
]

MAIN_OPEN = re.compile(r"<main(?:\s[^>]*)?>")

HEAD = """\
<!doctype html>
<!-- Generated by `leaf-dev corpus` from examples, regression pages, and the developer gallery. -->
<html lang="en">
<head>
<title>Leaf example corpus</title>
</head>
<body>
<main class="layout-column">
<p class="eyebrow">internal page corpus</p>
<h1>Every Leaf page fixture, composed</h1>
<p class="lede" id="corpus-lede">This internal stress surface puts every
authored page in one document so the browser suite can exercise their combined
weight and distributed controls. It is a test fixture, not the public examples
catalog.</p>

<section id="corpus-sources">
<lf-tabs id="corpus">
"""

FOOT = """\
</lf-tabs>
</section>
</main>
</body>
</html>
"""


def build_data() -> dict:
    """Compose corpus inputs with captures relative to the generated page."""
    sources = {}
    captures = {}
    for source, _ in TABS:
        companion = source.with_suffix(".data.json")
        if not companion.exists():
            continue
        document = json.loads(companion.read_text(encoding="utf-8"))
        for name, spec in document.pop("$captures", {}).items():
            capture_file = (source.parent / spec["file"]).resolve()
            relative_file = capture_file.relative_to(
                EXAMPLES_DIR.resolve(), walk_up=True
            )
            corpus_spec = {**spec, "file": relative_file.as_posix()}
            if name in captures:
                if captures[name] != corpus_spec:
                    sys.exit(
                        f"corpus examples contribute conflicting data capture {name!r}"
                    )
                continue
            captures[name] = corpus_spec
        for name, value in document.items():
            if name in sources and sources[name] != value:
                sys.exit(f"corpus examples contribute conflicting data source {name!r}")
            sources[name] = value
    return ({"$captures": captures} if captures else {}) | sources


def build() -> str:
    on_disk = {p.name for p in EXAMPLES_DIR.glob("*.html")} - {CORPUS.name}
    in_table = {stem + ".html" for stem, _ in PUBLIC_TABS}
    if on_disk != in_table:
        sys.exit(
            "public examples and the PUBLIC_TABS table disagree: "
            f"{sorted(on_disk ^ in_table)}"
        )
    owner = {"corpus": CORPUS.name, "corpus-lede": CORPUS.name}
    tabs = []
    authored_assets = []
    for source, label in TABS:
        stem = source.stem
        text = source.read_text(encoding="utf-8")
        parsed = SourceDocument(text)
        if parsed.css.strip():
            authored_assets.append(
                f"<!-- {source.name} authored styles -->\n<style>{parsed.css}</style>"
            )
        authored_assets.extend(
            f"<!-- {source.name} authored script -->\n<script"
            + "".join(
                f' {name}="{html.escape(value, quote=True)}"'
                for name, value in script["attrs"].items()
            )
            + f">{script['body']}</script>"
            for script in parsed.inline_scripts
        )
        for i in ["corpus-" + stem] + parsed.all_ids:
            if i in owner:
                sys.exit(
                    f"id '{i}' is in both {owner[i]} and {source.name}; rename one"
                )
            owner[i] = source.name
        # A page's own Layout (the class on its `<main>`) is its document's to declare;
        # a tab in the corpus is part of the corpus's column page, so only the body
        # carries over.
        opens = list(MAIN_OPEN.finditer(text))
        if len(opens) != 1 or text.count("</main>") != 1:
            sys.exit(f"{source.name}: expected exactly one <main>…</main>")
        body = text[opens[0].end() : text.rindex("</main>")].strip()
        # The tab's label is the example's own eyebrow, title-cased, so embedding both
        # makes the panel say its name twice. On screen the strip carries it; wherever
        # there is no strip — unupgraded, in print, in a copy — the theme paints the
        # label back onto the panel. The eyebrow is the copy that has nowhere to be.
        body = re.sub(r'^<p class="eyebrow">[^<]*</p>\s*', "", body)
        # lf-toc maps its closest main. After composition that is the corpus's outer
        # document, so retaining a source page's map would repeat one whole-corpus
        # outline in every tab rather than navigate that source page.
        body = CONTENTS_MAP.sub("", body)
        tabs.append(f'<lf-tab id="corpus-{stem}" label="{label}">\n{body}\n</lf-tab>\n')

    head = HEAD.replace("</head>", "\n".join(authored_assets) + "\n</head>")
    return head + "\n" + "\n".join(tabs) + "\n" + FOOT


def build_page() -> dict[str, bytes]:
    """The corpus's page directory: every element an example owns, with its modules.

    An element is the example's own when it ships the module that defines it,
    `widgets/<tag>.js`; a declaration without one narrows a layer widget for that page
    alone (a playground's fixed id) and stays out of the corpus. An owning example's
    other page files come along, since its modules import them.
    """
    declarations = {}
    files = {}
    for source, _ in TABS:
        page = source.with_suffix(".page")
        if not page.is_dir():
            continue
        registry = json.loads((page / "registry.json").read_text(encoding="utf-8"))
        owned = {
            tag: entry
            for tag, entry in registry.items()
            if (page / "widgets" / f"{tag}.js").is_file()
        }
        if not owned:
            continue
        for tag, entry in owned.items():
            if tag in declarations:
                sys.exit(f"corpus examples both declare {tag!r}")
            declarations[tag] = entry
        for path in sorted(page.rglob("*")):
            name = path.relative_to(page).as_posix()
            if not path.is_file() or name == "registry.json":
                continue
            if name in files and files[name] != path.read_bytes():
                sys.exit(f"corpus examples contribute conflicting page file {name!r}")
            files[name] = path.read_bytes()
    if not declarations:
        return {}
    registry = json.dumps(declarations, indent=2, ensure_ascii=False) + "\n"
    return {"registry.json": registry.encode(), **files}


def build_events() -> str:
    """Carry the threads embedded samples explicitly depend on.

    The corpus otherwise starts undecided; composing every example's history would
    settle unrelated controls before the corpus can exercise them.
    """
    combined = {}
    for source, _ in TABS:
        document = SourceDocument(source.read_text(encoding="utf-8"))
        selected = {
            thread
            for sample in document.samples
            for thread in sample["attrs"].get("data-sample-threads", "").split()
        }
        if not selected:
            continue
        events = [
            json.loads(line)
            for line in source.with_suffix(".jsonl").read_text().splitlines()
            if line.strip()
        ]
        # A declaration naming nothing is a typo here and nothing else: the history
        # is the example's own shipped log, so a thread absent from it will be absent
        # from every page built from this source. `sample_events` seeds what a log
        # holds, because a served page may legitimately hold none of it yet.
        if unknown := selected - thread_ids(events):
            sys.exit(
                f"{source.name} declares sample threads its log does not "
                f"hold: {', '.join(sorted(unknown))}"
            )
        for event in sample_events(document, events, selected):
            if event["id"] in combined and combined[event["id"]] != event:
                sys.exit(
                    f"corpus examples contribute conflicting event {event['id']!r}"
                )
            combined[event["id"]] = event
    return "".join(
        json.dumps(event, ensure_ascii=False) + "\n" for event in combined.values()
    )


@click.command()
def corpus() -> None:
    """Regenerate examples/corpus.html and its companions."""
    CORPUS.write_text(build(), encoding="utf-8")
    CORPUS_DATA.write_text(
        json.dumps(build_data(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    CORPUS_EVENTS.write_text(build_events(), encoding="utf-8")
    shutil.rmtree(CORPUS_PAGE, ignore_errors=True)
    for name, data in build_page().items():
        (CORPUS_PAGE / name).parent.mkdir(parents=True, exist_ok=True)
        (CORPUS_PAGE / name).write_bytes(data)
    print(CORPUS)
    print(CORPUS_DATA)
    print(CORPUS_EVENTS)
