"""Prepare the Git payload installers consume, with a compiled browser kernel.

The source tree contains no generated kernel bundles. CI builds this tree before
publishing it to the moving `prepared` branch; native marketplace and Pi updates
follow that branch. The website build prepares one beside the site, which its page
directories are vendored from and its container image installs (`leaf_dev.site`). Nothing compiles during installation, page init, export, or
custom-package authoring. Package widgets remain native ESM and import the same
widget-api entry as the compiled kernel, so their state has one owner.

The developer arm's payload layout preserves uv's workspace and each harness's
local marketplace layout. Only browser runtime JavaScript is replaced; source
paths retained in the distribution manifest enforce the private kernel boundary.
The Pi manifest excludes maintainer dependencies and compiler commands.
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path

import click
from leaf.layer import (
    compose_layer,
    kernel_runtime_paths,
    layer_inputs,
    payload_provenance,
)
from leaf.schema import PLUGIN_ROOT

from leaf_dev.arms import extract_payload


def prepare(output: Path) -> None:
    """Build a new installation tree from this checkout's tracked working files."""
    if output.exists():
        raise click.ClickException(f"installation destination already exists: {output}")
    extract_payload(output)

    composition = compose_layer(layer_inputs())
    with tempfile.TemporaryDirectory(prefix="leaf-distribution-") as directory:
        layer = Path(directory)
        (layer / "leaf.js").write_bytes(composition.top_files["leaf.js"])
        for sub in ("runtime", "widgets", "vendor"):
            for name, data in composition.directory_files[sub].items():
                target = layer / sub / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
        assets = output / "skills/leaf/assets"
        default_runtime = output / "skills/leaf/packages/default/runtime"
        for runtime in (assets / "runtime", default_runtime):
            for source in runtime.rglob("*.js"):
                source.unlink()
        subprocess.run(
            [
                "node",
                str(PLUGIN_ROOT / "build/runtime-bundle.mjs"),
                str(layer),
                str(assets),
            ],
            cwd=PLUGIN_ROOT,
            check=True,
        )

    package = json.loads((output / "package.json").read_text())
    (output / "package.json").write_text(
        json.dumps(
            {key: package[key] for key in ("name", "private", "type", "pi")}, indent=2
        )
        + "\n"
    )
    (output / "leaf-distribution.json").write_text(
        json.dumps(
            {
                "producer": payload_provenance(),
                "runtime_paths": sorted(kernel_runtime_paths()),
            },
            indent=2,
        )
        + "\n"
    )


@click.command("distribution")
@click.option(
    "--output",
    type=click.Path(path_type=Path),
    required=True,
    help="New installation-tree directory; must not already exist.",
)
def distribution(output: Path) -> None:
    """Build a prepared, compiler-free plugin installation tree."""
    prepare(output.resolve())
    click.echo(f"✓ Prepared installation → {output}")


def publish(output: Path) -> str | None:
    """Fast-forward prepared with a verified payload, retaining source ancestry.

    A serialized CI job publishes only the current main. The source is a second
    parent, so provenance and post-merge refresh can use Git ancestry without
    merging generated bytes into development. A normal push rejects any race.
    """
    metadata = json.loads((output / "leaf-distribution.json").read_text())
    producer = metadata["producer"]
    if producer["dirty"]:
        raise click.ClickException("refusing to publish a dirty source tree")

    def git(*args: str, env=None) -> str:
        return subprocess.run(
            ["git", *args],
            cwd=PLUGIN_ROOT,
            env=env,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()

    git("fetch", "origin", "main")
    source = git("rev-parse", f"{producer['commit']}^{{commit}}")
    if source != git("rev-parse", "origin/main"):
        return None
    previous = git("ls-remote", "origin", "refs/heads/prepared")
    parents = []
    if previous:
        git("fetch", "origin", "prepared")
        previous_commit = previous.split()[0]
        published = json.loads(git("show", f"{previous_commit}:leaf-distribution.json"))
        ancestry = subprocess.run(
            [
                "git",
                "merge-base",
                "--is-ancestor",
                published["producer"]["commit"],
                source,
            ],
            cwd=PLUGIN_ROOT,
            check=False,
        )
        if ancestry.returncode == 1:
            return None
        ancestry.check_returncode()
        parents = ["-p", previous_commit]
    with tempfile.TemporaryDirectory(prefix="leaf-distribution-index-") as directory:
        env = {**os.environ, "GIT_INDEX_FILE": str(Path(directory) / "index")}
        git("read-tree", "--empty", env=env)
        git(f"--work-tree={output}", "add", "--all", env=env)
        tree = git("write-tree", env=env)
    if previous and tree == git("rev-parse", f"{previous.split()[0]}^{{tree}}"):
        return previous.split()[0]
    commit = git(
        "commit-tree",
        tree,
        *parents,
        "-p",
        source,
        "-m",
        f"Prepare Leaf from {source}",
    )
    git("push", "origin", f"{commit}:refs/heads/prepared")
    return commit


@click.command("publish-distribution")
@click.argument("output", type=click.Path(path_type=Path, exists=True))
def publish_distribution(output: Path) -> None:
    """Publish the verified CI installation tree to the prepared branch."""
    commit = publish(output.resolve())
    click.echo(
        f"✓ Prepared → {commit}" if commit else "Source superseded; skipped publication"
    )
