#!/usr/bin/env python3
"""Generate examples/corpus.html: every authored page fixture on one page.

The corpus is derived test content — edit an example, regression page, or the
developer feature gallery and rerun this script (tests fail on a stale corpus). Each page's
<main> body keeps its ids but not its document-level contents sidebar. Every source
must therefore keep its ids disjoint, which this script enforces.
An example that owns an element (a page/registry.json declaration with its module under
page/widgets/) brings that element into the corpus through examples/corpus.page/, the
corpus's own page directory, so its markup still names a declared element there.
Usage: corpus.py  (no arguments; writes examples/corpus.html and its companions)
"""

import json
import re
import sys
from pathlib import Path

from example_data import regression_sources
from leaf.structure import SourceDocument
from leaf.thread_context import comment_ids, specimen_events

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
CORPUS = EXAMPLES_DIR / "corpus.html"
CORPUS_DATA = EXAMPLES_DIR / "corpus.data.json"
CORPUS_EVENTS = EXAMPLES_DIR / "corpus.jsonl"
CORPUS_PAGE = EXAMPLES_DIR / "corpus.page"
# Keep the short core pages first; specialist and regression surfaces follow.
PUBLIC_TABS = [
    ("review-a-plan", "Plan review"),
    ("triage-board", "Triage"),
    ("ideas-to-implement", "Ideas"),
    ("release-notes", "Notes"),
    ("log-retention", "Retention"),
    ("ship-review", "Ship review"),
    ("heat-loss", "Heat"),
    ("notification-playground", "Notification"),
    ("data-explorer", "Data explorer"),
    ("code-comparison", "Code comparison"),
    ("live-progress", "Live"),
    ("alert-review", "Alerts"),
    ("pr-walkthrough", "PR"),
    ("wt-merge", "Merge film"),
    ("security-boundary", "Security"),
    ("command-hub", "Command"),
]
DEVELOPER_TABS = [
    (EXAMPLES_DIR / "developer" / "feature-gallery.html", "Core features"),
    (EXAMPLES_DIR / "developer" / "swipe-gallery.html", "Swipe package"),
    (EXAMPLES_DIR / "developer" / "targeting-gallery.html", "Targeting package"),
    (
        EXAMPLES_DIR / "developer" / "visual-review-gallery.html",
        "Visual review package",
    ),
]
CONTENTS_MAP = re.compile(
    r"\s*<(aside|section)\b[^>]*>\s*<lf-toc\b[^>]*></lf-toc>\s*</\1>"
)
TABS = [
    *((EXAMPLES_DIR / f"{stem}.html", label) for stem, label in PUBLIC_TABS),
    *(
        (source, source.stem.replace("-", " ").title())
        for source in regression_sources()
    ),
    *DEVELOPER_TABS,
]

MAIN_OPEN = re.compile(r"<main(?:\s[^>]*)?>")

HEAD = """\
<!doctype html>
<!-- Generated by scripts/corpus.py from examples, regression pages, and the developer gallery. -->
<html lang="en">
<head>
<title>Leaf example corpus</title>
</head>
<body>
<main>
<p class="eyebrow">internal page corpus</p>
<h1>Every Leaf page fixture, composed</h1>
<p class="lede" id="corpus-lede">This internal stress surface puts every
authored page in one document so the browser suite can exercise their combined
weight and distributed controls. It is a test fixture, not the public examples
catalog.</p>

<lf-tabs id="corpus">
"""

FOOT = """\
</lf-tabs>
</main>
</body>
</html>
"""


def composed_data() -> dict:
    """Compose every example's captures and current values into one companion."""
    sources = {}
    captures = {}
    for source, _ in TABS:
        companion = source.with_suffix(".data.json")
        if not companion.exists():
            continue
        document = json.loads(companion.read_text(encoding="utf-8"))
        for name, spec in document.pop("$captures", {}).items():
            capture_file = (source.parent / spec["file"]).resolve()
            try:
                relative_file = capture_file.relative_to(EXAMPLES_DIR.resolve())
            except ValueError:
                sys.exit(f"{source.name}: data capture {name!r} is outside examples/")
            corpus_spec = {**spec, "file": relative_file.as_posix()}
            if name in captures:
                if captures[name] != corpus_spec:
                    sys.exit(
                        f"corpus examples contribute conflicting data capture {name!r}"
                    )
                continue
            captures[name] = corpus_spec
        for name, value in document.items():
            if name in sources and sources[name] != value:
                sys.exit(f"corpus examples contribute conflicting data source {name!r}")
            sources[name] = value
    return ({"$captures": captures} if captures else {}) | sources


def build() -> str:
    on_disk = {p.name for p in EXAMPLES_DIR.glob("*.html")} - {CORPUS.name}
    in_table = {stem + ".html" for stem, _ in PUBLIC_TABS}
    if on_disk != in_table:
        sys.exit(
            "public examples and the PUBLIC_TABS table disagree: "
            f"{sorted(on_disk ^ in_table)}"
        )
    developer_pages = set((EXAMPLES_DIR / "developer").glob("*.html"))
    declared_developer_pages = {source for source, _ in DEVELOPER_TABS}
    if developer_pages != declared_developer_pages:
        sys.exit(
            "developer pages and the DEVELOPER_TABS table disagree: "
            f"{sorted(path.name for path in developer_pages ^ declared_developer_pages)}"
        )

    owner = {"corpus": CORPUS.name, "corpus-lede": CORPUS.name}
    tabs = []
    authored_assets = []
    for source, label in TABS:
        stem = source.stem
        text = source.read_text(encoding="utf-8")
        parsed = SourceDocument(text)
        if parsed.css.strip():
            authored_assets.append(
                f"<!-- {source.name} authored styles -->\n<style>{parsed.css}</style>"
            )
        authored_assets.extend(
            f'<!-- {source.name} authored module -->\n<script type="module">'
            f"{script['body']}</script>"
            for script in parsed.inline_scripts
        )
        for i in ["corpus-" + stem] + parsed.all_ids:
            if i in owner:
                sys.exit(
                    f"id '{i}' is in both {owner[i]} and {source.name}; rename one"
                )
            owner[i] = source.name
        # A page's own width (`<main data-width>`, a sheet) is its document's to declare;
        # a tab in the corpus is part of the corpus's page, so only the body carries over.
        opens = list(MAIN_OPEN.finditer(text))
        if len(opens) != 1 or text.count("</main>") != 1:
            sys.exit(f"{source.name}: expected exactly one <main>…</main>")
        body = text[opens[0].end() : text.rindex("</main>")].strip()
        # The tab's label is the example's own eyebrow, title-cased, so embedding both
        # makes the panel say its name twice. On screen the strip carries it; wherever
        # there is no strip — unupgraded, in print, in a copy — the theme paints the
        # label back onto the panel. The eyebrow is the copy that has nowhere to be.
        body = re.sub(r'^<p class="eyebrow">[^<]*</p>\s*', "", body)
        # lf-toc maps its closest main. After composition that is the corpus's outer
        # document, so retaining a source page's map would repeat one whole-corpus
        # outline in every tab rather than navigate that source page.
        body = CONTENTS_MAP.sub("", body)
        tabs.append(f'<lf-tab id="corpus-{stem}" label="{label}">\n{body}\n</lf-tab>\n')

    head = HEAD.replace("</head>", "\n".join(authored_assets) + "\n</head>")
    return head + "\n" + "\n".join(tabs) + "\n" + FOOT


def build_page() -> dict[str, bytes]:
    """The corpus's page directory: every element an example owns, with its modules.

    An element is the example's own when it ships the module that defines it,
    `widgets/<tag>.js`; a declaration without one narrows a layer widget for that page
    alone (a playground's fixed id) and stays out of the corpus. An owning example's
    other page files come along, since its modules import them.
    """
    declarations = {}
    files = {}
    for source, _ in TABS:
        page = source.with_suffix(".page")
        if not page.is_dir():
            continue
        registry = json.loads((page / "registry.json").read_text(encoding="utf-8"))
        owned = {
            tag: entry
            for tag, entry in registry.items()
            if (page / "widgets" / f"{tag}.js").is_file()
        }
        if not owned:
            continue
        for tag, entry in owned.items():
            if tag in declarations:
                sys.exit(f"corpus examples both declare {tag!r}")
            declarations[tag] = entry
        for path in sorted(page.rglob("*")):
            name = path.relative_to(page).as_posix()
            if not path.is_file() or name == "registry.json":
                continue
            if name in files and files[name] != path.read_bytes():
                sys.exit(f"corpus examples contribute conflicting page file {name!r}")
            files[name] = path.read_bytes()
    if not declarations:
        return {}
    registry = json.dumps(declarations, indent=2, ensure_ascii=False) + "\n"
    return {"registry.json": registry.encode(), **files}


def build_data() -> dict:
    """Compose the package sources needed by the examples embedded in the corpus."""
    return composed_data()


def build_events() -> str:
    """Carry the conversations embedded specimens explicitly depend on.

    The corpus otherwise starts undecided; composing every example's history would
    settle unrelated controls before the corpus can exercise them.
    """
    combined = {}
    for source, _ in TABS:
        document = SourceDocument(source.read_text(encoding="utf-8"))
        selected = {
            root
            for specimen in document.specimens
            for root in specimen["attrs"].get("data-specimen-threads", "").split()
        }
        if not selected:
            continue
        events = [
            json.loads(line)
            for line in source.with_suffix(".jsonl").read_text().splitlines()
            if line.strip()
        ]
        # A declaration naming nothing is a typo here and nothing else: the history
        # is the example's own shipped log, so a root absent from it will be absent
        # from every page built from this source. `specimen_events` seeds what a log
        # holds, because a served page may legitimately hold none of it yet.
        if unknown := selected - comment_ids(events):
            sys.exit(
                f"{source.name} declares specimen conversations its log does not "
                f"hold: {', '.join(sorted(unknown))}"
            )
        for event in specimen_events(document, events, selected):
            if event["id"] in combined and combined[event["id"]] != event:
                sys.exit(
                    f"corpus examples contribute conflicting event {event['id']!r}"
                )
            combined[event["id"]] = event
    return "".join(
        json.dumps(event, ensure_ascii=False) + "\n" for event in combined.values()
    )


def main() -> None:
    CORPUS.write_text(build(), encoding="utf-8")
    CORPUS_DATA.write_text(
        json.dumps(build_data(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    CORPUS_EVENTS.write_text(build_events(), encoding="utf-8")
    for old in (
        sorted(CORPUS_PAGE.rglob("*"), reverse=True) if CORPUS_PAGE.exists() else []
    ):
        old.unlink() if old.is_file() else old.rmdir()
    for name, data in build_page().items():
        (CORPUS_PAGE / name).parent.mkdir(parents=True, exist_ok=True)
        (CORPUS_PAGE / name).write_bytes(data)
    print(CORPUS)
    print(CORPUS_DATA)
    print(CORPUS_EVENTS)


if __name__ == "__main__":
    main()
