#!/usr/bin/env python3
"""Generate examples/corpus.html: every authored page fixture on one page.

The corpus is derived test content — edit the public examples or the developer
feature gallery and rerun this script (tests fail on a stale corpus). Each page's
<main> body is embedded verbatim, so ids in the corpus are the ids in the sources;
that requires every source to keep its ids disjoint, which this script enforces.
Usage: corpus.py  (no arguments; writes examples/corpus.html)
"""

import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
CORPUS = EXAMPLES_DIR / "corpus.html"
CORPUS_DATA = EXAMPLES_DIR / "corpus.data.json"
# Order is editorial: move from a focused choice through evidence and live work to the
# specialized command surface and two conversation reviews, then the developer gallery.
PUBLIC_TABS = [
    ("design-decision", "Decision"),
    ("heat-loss", "Heat"),
    ("live-progress", "Live"),
    ("postmortem", "Postmortem"),
    ("pr-walkthrough", "PR"),
    ("release-notes", "Notes"),
    ("triage-board", "Triage"),
    ("command-hub", "Command"),
    ("ship-review", "Ship review"),
    ("log-retention", "Retention"),
]
FEATURE_GALLERY = EXAMPLES_DIR / "developer" / "feature-gallery.html"
TABS = [
    *((EXAMPLES_DIR / f"{stem}.html", label) for stem, label in PUBLIC_TABS),
    (FEATURE_GALLERY, "Features"),
]

HEAD = """\
<!doctype html>
<!-- Generated by scripts/corpus.py from the public examples and developer gallery. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Leaf example corpus</title>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'">
<link rel="stylesheet" href="/theme.css">
<script type="module" src="/leaf.js"></script>
</head>
<body>
<main>
<p class="eyebrow">internal page corpus</p>
<h1>Every Leaf page fixture, composed</h1>
<p class="lede" id="corpus-lede">This internal stress surface puts every
authored page in one document so the browser suite can exercise their combined
weight and distributed controls. It is a test fixture, not the public examples
catalog.</p>

<lf-tabs id="corpus">
"""

FOOT = """\
</lf-tabs>
</main>
</body>
</html>
"""


class _Scan(HTMLParser):
    """Collect element ids from one example."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.ids = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if attrs.get("id"):
            self.ids.append(attrs["id"])


def build() -> str:
    on_disk = {p.name for p in EXAMPLES_DIR.glob("*.html")} - {CORPUS.name}
    in_table = {stem + ".html" for stem, _ in PUBLIC_TABS}
    if on_disk != in_table:
        sys.exit(
            "public examples and the PUBLIC_TABS table disagree: "
            f"{sorted(on_disk ^ in_table)}"
        )
    developer_pages = set((EXAMPLES_DIR / "developer").glob("*.html"))
    if developer_pages != {FEATURE_GALLERY}:
        sys.exit(
            "developer feature fixtures must share feature-gallery.html: "
            f"{sorted(path.name for path in developer_pages ^ {FEATURE_GALLERY})}"
        )

    owner = {"corpus": CORPUS.name, "corpus-lede": CORPUS.name}
    tabs = []
    for source, label in TABS:
        stem = source.stem
        text = source.read_text(encoding="utf-8")
        scan = _Scan()
        scan.feed(text)
        for i in ["corpus-" + stem] + scan.ids:
            if i in owner:
                sys.exit(
                    f"id '{i}' is in both {owner[i]} and {source.name}; rename one"
                )
            owner[i] = source.name
        if text.count("<main>") != 1 or text.count("</main>") != 1:
            sys.exit(f"{source.name}: expected exactly one <main>…</main>")
        body = text[
            text.index("<main>") + len("<main>") : text.rindex("</main>")
        ].strip()
        # The tab's label is the example's own eyebrow, title-cased, so embedding both
        # makes the panel say its name twice. On screen the strip carries it; wherever
        # there is no strip — unupgraded, in print, in a copy — the theme paints the
        # label back onto the panel. The eyebrow is the copy that has nowhere to be.
        body = re.sub(r'^<p class="eyebrow">[^<]*</p>\s*', "", body)
        tabs.append(f'<lf-tab id="corpus-{stem}" label="{label}">\n{body}\n</lf-tab>\n')

    return HEAD + "\n" + "\n".join(tabs) + "\n" + FOOT


def build_data() -> dict:
    """Compose the package sources needed by the examples embedded in the corpus."""
    sources = {}
    captures = {}
    for source, _ in TABS:
        companion = source.with_suffix(".data.json")
        if not companion.exists():
            continue
        document = json.loads(companion.read_text(encoding="utf-8"))
        for name, spec in document.pop("$captures", {}).items():
            if name in captures and captures[name] != spec:
                sys.exit(
                    f"corpus examples contribute conflicting data capture {name!r}"
                )
            captures[name] = spec
        for name, value in document.items():
            if name in sources and sources[name] != value:
                sys.exit(f"corpus examples contribute conflicting data source {name!r}")
            sources[name] = value
    return ({"$captures": captures} if captures else {}) | sources


def main() -> None:
    CORPUS.write_text(build(), encoding="utf-8")
    CORPUS_DATA.write_text(
        json.dumps(build_data(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(CORPUS)
    print(CORPUS_DATA)


if __name__ == "__main__":
    main()
