#!/usr/bin/env python3
"""Generate examples/gallery.html: every example on one page, one lf-tab each.

The gallery is derived content — edit the sibling examples and rerun this
script (tests fail on a stale gallery). Each example's <main> body is embedded
verbatim, so ids in the gallery are the ids in the sources; that requires the
examples to keep their ids disjoint across files, which this script enforces.
Usage: gallery.py  (no arguments; writes examples/gallery.html)
"""

import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
GALLERY = EXAMPLES_DIR / "gallery.html"
GALLERY_DATA = EXAMPLES_DIR / "gallery.data.json"
# Order is editorial: the first tab is the one a reader lands on, and
# parallel-workstreams reads best last (it's tabs inside a tab).
TABS = [
    ("ship-review", "Ship review"),
    ("design-decision", "Design decision"),
    ("postmortem", "Postmortem"),
    ("pr-walkthrough", "PR walkthrough"),
    ("live-progress", "Live progress"),
    ("heat-loss", "Heating review"),
    ("triage-board", "Triage board"),
    ("command-hub", "Command hub"),
    ("release-notes", "Release notes"),
    ("parallel-workstreams", "Parallel workstreams"),
]

HEAD = """\
<!doctype html>
<!-- Generated by scripts/gallery.py from the sibling examples; edit those and rerun it. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Leaf examples gallery</title>
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'">
<link rel="stylesheet" href="/theme.css">
<script type="module" src="/leaf.js"></script>
</head>
<body>
<main>
<p class="eyebrow">examples gallery</p>
<h1>The leaf gallery, on one page</h1>
<p class="lede" id="gal-lede">The shipped examples, one per tab, every widget
live: boards drag, options take a pick, diagrams render. Every project, name,
and number here is invented. Switch tabs freely (that's your view alone); select
any text to comment on the example it belongs to.</p>

<lf-tabs id="gallery">
"""

FOOT = """\
</lf-tabs>
</main>
</body>
</html>
"""


class _Scan(HTMLParser):
    """Collect element ids from one example."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.ids = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if attrs.get("id"):
            self.ids.append(attrs["id"])


def build() -> str:
    on_disk = {p.name for p in EXAMPLES_DIR.glob("*.html")} - {GALLERY.name}
    in_table = {stem + ".html" for stem, _ in TABS}
    if on_disk != in_table:
        sys.exit(f"examples/ and the TABS table disagree: {sorted(on_disk ^ in_table)}")

    owner = {"gallery": GALLERY.name, "gal-lede": GALLERY.name}
    tabs = []
    for stem, label in TABS:
        source = EXAMPLES_DIR / f"{stem}.html"
        text = source.read_text(encoding="utf-8")
        scan = _Scan()
        scan.feed(text)
        for i in ["gal-" + stem] + scan.ids:
            if i in owner:
                sys.exit(
                    f"id '{i}' is in both {owner[i]} and {source.name}; rename one"
                )
            owner[i] = source.name
        if text.count("<main>") != 1 or text.count("</main>") != 1:
            sys.exit(f"{source.name}: expected exactly one <main>…</main>")
        body = text[
            text.index("<main>") + len("<main>") : text.rindex("</main>")
        ].strip()
        # The tab's label is the example's own eyebrow, title-cased, so embedding both
        # makes the panel say its name twice. On screen the strip carries it; wherever
        # there is no strip — unupgraded, in print, in a copy — the theme paints the
        # label back onto the panel. The eyebrow is the copy that has nowhere to be.
        body = re.sub(r'^<p class="eyebrow">[^<]*</p>\s*', "", body)
        tabs.append(f'<lf-tab id="gal-{stem}" label="{label}">\n{body}\n</lf-tab>\n')

    return HEAD + "\n" + "\n".join(tabs) + "\n" + FOOT


def build_data() -> dict:
    """Compose the package sources needed by the examples embedded in the gallery."""
    sources = {}
    for stem, _ in TABS:
        companion = EXAMPLES_DIR / f"{stem}.data.json"
        if not companion.exists():
            continue
        for name, value in json.loads(companion.read_text(encoding="utf-8")).items():
            if name in sources and sources[name] != value:
                sys.exit(
                    f"gallery examples contribute conflicting data source {name!r}"
                )
            sources[name] = value
    return sources


def main() -> None:
    GALLERY.write_text(build(), encoding="utf-8")
    GALLERY_DATA.write_text(
        json.dumps(build_data(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(GALLERY)
    print(GALLERY_DATA)


if __name__ == "__main__":
    main()
