#!/usr/bin/env python3
"""Write the x- key table in docs/packages.html from the registry's $keys.

The table is derived content — the registry documents each key once ($keys), agents
query that same entry, and this writes it to the reader. Edit the registry and rerun
this script (a test fails on a stale table). The rows land between
the two marker comments in the page; everything else in the file is authored.
Usage: keydocs.py  (no arguments; rewrites docs/packages.html in place)
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "plugins" / "leaf" / "skills" / "leaf" / "assets" / "registry.json"
DOCS_PAGE = ROOT / "docs" / "packages.html"
OPEN = "<!-- $keys: generated by scripts/keydocs.py from the registry; edit that -->"
CLOSE = "<!-- /$keys -->"


def prose(text: str) -> str:
    """A $keys paragraph as HTML: escaped, with `code` spans marked up."""
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", html.escape(text, quote=False))


def rows() -> str:
    keys = json.loads(REGISTRY.read_text(encoding="utf-8"))["$keys"]
    out = []
    for key in sorted(k for k in keys if k != "description"):
        out.append(
            f"<tr>\n<td><code>{key}</code></td>\n<td>{prose(keys[key])}</td>\n</tr>"
        )
    return "\n".join(out)


def build(page: str) -> str:
    start = page.index(OPEN) + len(OPEN)
    end = page.index(CLOSE)
    return page[:start] + "\n" + rows() + "\n" + page[end:]


def main() -> None:
    page = DOCS_PAGE.read_text(encoding="utf-8")
    if page.count(OPEN) != 1 or page.count(CLOSE) != 1:
        sys.exit(f"{DOCS_PAGE}: expected one {OPEN!r} … {CLOSE!r} region")
    DOCS_PAGE.write_text(build(page), encoding="utf-8")
    print(DOCS_PAGE)


if __name__ == "__main__":
    main()
