#!/usr/bin/env python3
"""Write docs/registry.html's x- key index from the registry's $keys.

The reference is derived content — the registry documents each key once ($keys), the
agents query that same entry, and this writes a browsable reference for the reader.
Edit the registry and rerun this script (a test fails on stale output). The index lands
between the two marker comments; everything else is authored. Usage: keydocs.py (no
arguments; rewrites docs/registry.html in place)
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "skills" / "leaf" / "assets" / "registry.json"
DOCS_PAGE = ROOT / "docs" / "registry.html"
OPEN = "<!-- $keys: generated by scripts/keydocs.py from the registry; edit that -->"
CLOSE = "<!-- /$keys -->"
COLLAPSED_DETAIL_WORDS = 30


def prose(text: str) -> str:
    """A $keys paragraph as HTML: escaped, with `code` spans marked up."""
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", html.escape(text, quote=False))


def summary(text: str) -> tuple[str, str]:
    """Return the visible summary and any substantial detail to disclose."""
    first, separator, detail = text.partition(". ")
    if not separator or len(detail.split()) < COLLAPSED_DETAIL_WORDS:
        return text, ""
    return first + ".", detail


def reference() -> str:
    keys = json.loads(REGISTRY.read_text(encoding="utf-8"))["$keys"]
    names = sorted(key for key in keys if key != "description")
    index = "\n".join(f'<a href="#{key}"><code>{key}</code></a>' for key in names)
    entries = []
    for key in names:
        lead, detail = summary(keys[key])
        contract = ""
        if detail:
            contract = (
                '<details class="reference-more">\n'
                f'<summary aria-label="Full {key} contract">Full contract</summary>\n'
                f"<p>{prose(detail)}</p>\n"
                "</details>\n"
            )
        entries.append(
            f'<section class="reference-entry" id="{key}">\n'
            f"<h3><code>{key}</code></h3>\n"
            '<div class="reference-copy">\n'
            f"<p>{prose(lead)}</p>\n"
            f"{contract}"
            "</div>\n"
            "</section>"
        )
    rendered_entries = "\n".join(entries)
    return (
        '<nav class="reference-index" aria-label="Registry keys">\n'
        f"{index}\n"
        "</nav>\n"
        '<div class="reference-list">\n'
        f"{rendered_entries}\n"
        "</div>"
    )


def build(page: str) -> str:
    start = page.index(OPEN) + len(OPEN)
    end = page.index(CLOSE)
    return page[:start] + "\n" + reference() + "\n" + page[end:]


def main() -> None:
    page = DOCS_PAGE.read_text(encoding="utf-8")
    if page.count(OPEN) != 1 or page.count(CLOSE) != 1:
        sys.exit(f"{DOCS_PAGE}: expected one {OPEN!r} … {CLOSE!r} region")
    DOCS_PAGE.write_text(build(page), encoding="utf-8")
    print(DOCS_PAGE)


if __name__ == "__main__":
    main()
